info:
  contact:
    email: muhammetandic@gmail.com
    name: Muhammet Andiç
  description: AntPos Basic Pos App API Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: AntPos API
  version: "1.0"
paths: {}
swagger: "2.0"
